server:
  port: 2007
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HongMu7/scConfig.git
          search-paths: config-repo
          username: HongMu7
          password: a735393011

hongmu: prod config